name: Check formatting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  schedule:
    - cron: "0 8 * * *"

jobs:
  check-code:
    runs-on: ubuntu-22.04
    container: ghcr.io/scientificcomputing/fenics-gmsh:2023-04-21

    steps:
      - uses: actions/checkout@v3

      - name: Install code
        run: python3 -m pip install .[dev]

      - name: Flake8 code
        run: python3 -m flake8 -v

      - name: Mypy check
        run: python3 -m mypy -v src/
